"""
Trinus Viabilidade - Base de cidades brasileiras por estado.

Lista abrangente de municípios agrupados por UF, usada para o seletor
de cidades com busca na interface.
"""

CIDADES_POR_ESTADO: dict[str, list[str]] = {
    "AC": [
        "Rio Branco", "Cruzeiro do Sul", "Sena Madureira", "Tarauacá",
        "Feijó", "Brasileia", "Senador Guiomard", "Epitaciolândia",
        "Xapuri", "Plácido de Castro", "Mâncio Lima", "Acrelândia",
        "Porto Acre", "Bujari", "Capixaba",
    ],
    "AL": [
        "Maceió", "Arapiraca", "Rio Largo", "Palmeira dos Índios",
        "União dos Palmares", "Penedo", "São Miguel dos Campos",
        "Marechal Deodoro", "Delmiro Gouveia", "Campo Alegre",
        "Coruripe", "Santana do Ipanema", "Murici", "Girau do Ponciano",
        "Matriz de Camaragibe", "Atalaia", "Pilar", "Teotônio Vilela",
        "São Luís do Quitunde", "Arapiraca",
    ],
    "AM": [
        "Manaus", "Parintins", "Itacoatiara", "Manacapuru", "Coari",
        "Tefé", "Tabatinga", "Maués", "Iranduba", "Humaitá",
        "São Gabriel da Cachoeira", "Autazes", "Lábrea",
        "Presidente Figueiredo", "Benjamin Constant", "Manicoré",
        "Nova Olinda do Norte", "Borba", "Rio Preto da Eva",
        "Careiro da Várzea",
    ],
    "AP": [
        "Macapá", "Santana", "Laranjal do Jari", "Oiapoque",
        "Mazagão", "Porto Grande", "Tartarugalzinho", "Pedra Branca do Amapari",
        "Vitória do Jari", "Calçoene", "Amapá", "Ferreira Gomes",
        "Pracuúba", "Serra do Navio", "Cutias",
    ],
    "BA": [
        "Salvador", "Feira de Santana", "Vitória da Conquista", "Camaçari",
        "Itabuna", "Juazeiro", "Lauro de Freitas", "Ilhéus", "Jequié",
        "Teixeira de Freitas", "Barreiras", "Alagoinhas", "Porto Seguro",
        "Simões Filho", "Paulo Afonso", "Eunápolis",
        "Santo Antônio de Jesus", "Valença", "Candeias",
        "Luís Eduardo Magalhães", "Itaberaba", "Cruz das Almas",
        "Serrinha", "Irecê", "Jacobina", "Dias d'Ávila", "Guanambi",
        "Brumado", "Itapetinga", "Conceição do Coité", "Campo Formoso",
        "Senhor do Bonfim", "Santo Amaro", "Mata de São João",
        "Entre Rios", "Mucuri", "Itamaraju", "Medeiros Neto",
    ],
    "CE": [
        "Fortaleza", "Caucaia", "Juazeiro do Norte", "Maracanaú",
        "Sobral", "Crato", "Itapipoca", "Maranguape", "Iguatu",
        "Pacatuba", "Quixadá", "Aquiraz", "Cascavel", "Canindé",
        "Tianguá", "Crateús", "Pacajus", "Aracati", "Russas",
        "Eusébio", "São Gonçalo do Amarante", "Horizonte",
        "Limoeiro do Norte", "Tauá", "Camocim", "Acopiara",
        "Icó", "Morada Nova", "Beberibe", "Trairi",
    ],
    "DF": [
        "Brasília", "Taguatinga", "Ceilândia", "Samambaia",
        "Águas Claras", "Gama", "Santa Maria", "Recanto das Emas",
        "Sobradinho", "Planaltina", "Guará", "Vicente Pires",
        "Sudoeste", "Lago Sul", "Lago Norte", "Park Way",
        "Jardim Botânico", "Noroeste", "Arniqueira",
    ],
    "ES": [
        "Vitória", "Vila Velha", "Serra", "Cariacica", "Linhares",
        "Cachoeiro de Itapemirim", "São Mateus", "Guarapari",
        "Colatina", "Aracruz", "Viana", "Nova Venécia",
        "Barra de São Francisco", "São Gabriel da Palha",
        "Afonso Cláudio", "Marataízes", "Domingos Martins",
        "Fundão", "Pedro Canário", "Ibatiba", "Anchieta",
        "Piúma", "Itapemirim", "Presidente Kennedy",
    ],
    "GO": [
        "Goiânia", "Aparecida de Goiânia", "Anápolis", "Rio Verde",
        "Luziânia", "Águas Lindas de Goiás", "Valparaíso de Goiás",
        "Trindade", "Formosa", "Novo Gama", "Itumbiara",
        "Senador Canedo", "Catalão", "Jataí", "Planaltina",
        "Caldas Novas", "Santo Antônio do Descoberto",
        "Cidade Ocidental", "Goianésia", "Inhumas", "Mineiros",
        "Cristalina", "Morrinhos", "Quirinópolis", "Porangatu",
        "Ipameri", "Niquelândia", "Itaberaí", "Jaraguá",
        "Pirenópolis", "Goianápolis", "Goiatuba",
        "São Luís de Montes Belos",
    ],
    "MA": [
        "São Luís", "Imperatriz", "São José de Ribamar", "Timon",
        "Caxias", "Codó", "Paço do Lumiar", "Açailândia", "Bacabal",
        "Santa Inês", "Balsas", "Barra do Corda", "Coroatá",
        "Chapadinha", "Pinheiro", "Itapecuru Mirim", "Buriticupu",
        "Estreito", "Zé Doca", "Pedreiras", "Santa Luzia",
        "Presidente Dutra", "Viana", "Grajaú",
    ],
    "MG": [
        "Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora",
        "Betim", "Montes Claros", "Ribeirão das Neves", "Uberaba",
        "Governador Valadares", "Ipatinga", "Sete Lagoas",
        "Divinópolis", "Santa Luzia", "Ibirité", "Poços de Caldas",
        "Patos de Minas", "Teófilo Otoni", "Pouso Alegre",
        "Barbacena", "Sabará", "Varginha", "Conselheiro Lafaiete",
        "Araguari", "Itabira", "Passos", "Coronel Fabriciano",
        "Muriaé", "Araxá", "Lavras", "Nova Lima", "Itajubá",
        "Caratinga", "Alfenas", "Ituiutaba", "Ubá", "Manhuaçu",
        "Pedro Leopoldo", "Timóteo", "Ouro Preto",
        "São João del-Rei", "Unaí", "Curvelo", "Vespasiano",
        "Lagoa Santa", "Patrocínio", "João Monlevade",
        "Diamantina", "Januária", "Iturama", "Frutal",
    ],
    "MS": [
        "Campo Grande", "Dourados", "Três Lagoas", "Corumbá",
        "Ponta Porã", "Naviraí", "Nova Andradina", "Aquidauana",
        "Sidrolândia", "Maracaju", "Paranaíba", "Amambai",
        "Rio Brilhante", "Coxim", "Chapadão do Sul", "Jardim",
        "São Gabriel do Oeste", "Ivinhema", "Mundo Novo",
        "Bataguassu", "Costa Rica", "Cassilândia",
    ],
    "MT": [
        "Cuiabá", "Várzea Grande", "Rondonópolis", "Sinop",
        "Tangará da Serra", "Cáceres", "Sorriso", "Lucas do Rio Verde",
        "Primavera do Leste", "Barra do Garças", "Alta Floresta",
        "Nova Mutum", "Pontes e Lacerda", "Campo Novo do Parecis",
        "Colíder", "Juína", "Confresa", "Campo Verde",
        "Sapezal", "Juara", "Guarantã do Norte", "Poconé",
        "Diamantino", "Chapada dos Guimarães", "Água Boa",
    ],
    "PA": [
        "Belém", "Ananindeua", "Santarém", "Marabá", "Castanhal",
        "Parauapebas", "Abaetetuba", "Cametá", "Marituba",
        "Itaituba", "Bragança", "Altamira", "Tailândia",
        "Barcarena", "Tucuruí", "Redenção", "Paragominas",
        "Salinópolis", "Capanema", "Breves", "São Félix do Xingu",
        "Conceição do Araguaia", "Xinguara", "Benevides",
        "Oriximiná", "Igarapé-Açu",
    ],
    "PB": [
        "João Pessoa", "Campina Grande", "Santa Rita", "Patos",
        "Bayeux", "Sousa", "Cabedelo", "Cajazeiras", "Guarabira",
        "Sapé", "Mamanguape", "Solânea", "Monteiro", "Queimadas",
        "Conde", "Pombal", "Esperança", "São Bento",
        "Rio Tinto", "Itaporanga", "Picuí",
    ],
    "PE": [
        "Recife", "Jaboatão dos Guararapes", "Olinda", "Caruaru",
        "Petrolina", "Paulista", "Cabo de Santo Agostinho",
        "Camaragibe", "Garanhuns", "Vitória de Santo Antão",
        "Igarassu", "São Lourenço da Mata", "Abreu e Lima",
        "Serra Talhada", "Araripina", "Santa Cruz do Capibaribe",
        "Gravatá", "Carpina", "Goiana", "Arcoverde",
        "Belo Jardim", "Escada", "Surubim", "Bezerros",
    ],
    "PI": [
        "Teresina", "Parnaíba", "Picos", "Piripiri", "Floriano",
        "Campo Maior", "Barras", "Pedro II", "Oeiras",
        "José de Freitas", "Esperantina", "Altos",
        "São Raimundo Nonato", "Corrente", "União",
        "Uruçuí", "Bom Jesus", "Luís Correia",
    ],
    "PR": [
        "Curitiba", "Londrina", "Maringá", "Ponta Grossa",
        "Cascavel", "São José dos Pinhais", "Foz do Iguaçu",
        "Colombo", "Guarapuava", "Paranaguá", "Araucária",
        "Toledo", "Apucarana", "Pinhais", "Campo Largo",
        "Arapongas", "Almirante Tamandaré", "Umuarama",
        "Piraquara", "Cambé", "Sarandi", "Fazenda Rio Grande",
        "Campo Mourão", "Francisco Beltrão", "Pato Branco",
        "Cianorte", "Telêmaco Borba", "Castro", "Rolândia",
        "Irati", "Paranavaí", "Lapa", "União da Vitória",
        "Cornélio Procópio", "Medianeira", "Palotina",
        "Matinhos", "Pontal do Paraná", "Guaratuba",
    ],
    "RJ": [
        "Rio de Janeiro", "São Gonçalo", "Duque de Caxias",
        "Nova Iguaçu", "Niterói", "Belford Roxo",
        "Campos dos Goytacazes", "São João de Meriti", "Petrópolis",
        "Volta Redonda", "Magé", "Itaboraí", "Macaé", "Mesquita",
        "Nova Friburgo", "Barra Mansa", "Maricá", "Cabo Frio",
        "Nilópolis", "Angra dos Reis", "Queimados", "Teresópolis",
        "Resende", "Rio das Ostras", "Araruama",
        "São Pedro da Aldeia", "Japeri", "Saquarema", "Itaguaí",
        "Três Rios", "Guapimirim", "Itaperuna", "Mangaratiba",
        "Búzios", "Paraty", "Miguel Pereira", "Vassouras",
    ],
    "RN": [
        "Natal", "Mossoró", "Parnamirim", "São Gonçalo do Amarante",
        "Macaíba", "Ceará-Mirim", "Caicó", "Açu", "Currais Novos",
        "João Câmara", "Santa Cruz", "Nova Cruz", "Pau dos Ferros",
        "São José de Mipibu", "Apodi", "Extremoz", "Touros",
        "São Miguel", "Tibau do Sul", "Nísia Floresta",
    ],
    "RO": [
        "Porto Velho", "Ji-Paraná", "Ariquemes", "Vilhena",
        "Cacoal", "Rolim de Moura", "Jaru", "Guajará-Mirim",
        "Ouro Preto do Oeste", "Pimenta Bueno", "Buritis",
        "Machadinho d'Oeste", "Espigão d'Oeste", "Nova Mamoré",
        "Colorado do Oeste",
    ],
    "RR": [
        "Boa Vista", "Rorainópolis", "Caracaraí", "Alto Alegre",
        "Pacaraima", "Cantá", "Mucajaí", "Bonfim",
        "São João da Baliza", "Normandia",
    ],
    "RS": [
        "Porto Alegre", "Caxias do Sul", "Pelotas", "Canoas",
        "Santa Maria", "Gravataí", "Viamão", "Novo Hamburgo",
        "São Leopoldo", "Rio Grande", "Alvorada", "Passo Fundo",
        "Sapucaia do Sul", "Cachoeirinha", "Santa Cruz do Sul",
        "Uruguaiana", "Bagé", "Lajeado", "Bento Gonçalves",
        "Erechim", "Guaíba", "Ijuí", "Sapiranga", "Santana do Livramento",
        "Alegrete", "Esteio", "Cachoeira do Sul", "São Borja",
        "Cruz Alta", "Venâncio Aires", "Montenegro",
        "Farroupilha", "Tramandaí", "Capão da Canoa", "Torres",
        "Xangri-lá", "Gramado", "Canela", "Carlos Barbosa",
        "Garibaldi", "Flores da Cunha", "São José do Norte",
        "Camaquã", "Taquara", "Estância Velha",
    ],
    "SC": [
        "Florianópolis", "Joinville", "Blumenau", "São José",
        "Chapecó", "Criciúma", "Itajaí", "Jaraguá do Sul",
        "Palhoça", "Lages", "Balneário Camboriú", "Brusque",
        "Tubarão", "São Bento do Sul", "Caçador", "Concórdia",
        "Camboriú", "Navegantes", "Rio do Sul", "Araranguá",
        "Gaspar", "Biguaçu", "Indaial", "Içara", "Mafra",
        "Canoinhas", "Imbituba", "Laguna", "Xanxerê", "Joaçaba",
        "Videira", "São Francisco do Sul", "Itapema", "Penha",
        "Bombinhas", "Porto Belo", "Tijucas", "Garopaba",
        "Governador Celso Ramos", "Piçarras",
    ],
    "SE": [
        "Aracaju", "Nossa Senhora do Socorro", "Lagarto",
        "Itabaiana", "São Cristóvão", "Estância", "Tobias Barreto",
        "Itabaianinha", "Simão Dias", "Capela", "Propriá",
        "Nossa Senhora da Glória", "Barra dos Coqueiros",
        "Carmópolis", "Laranjeiras",
    ],
    "SP": [
        "São Paulo", "Guarulhos", "Campinas", "São Bernardo do Campo",
        "Santo André", "São José dos Campos", "Osasco",
        "Ribeirão Preto", "Sorocaba", "Mauá",
        "São José do Rio Preto", "Santos", "Mogi das Cruzes",
        "Diadema", "Jundiaí", "Piracicaba", "Carapicuíba",
        "Bauru", "Itaquaquecetuba", "São Vicente", "Franca",
        "Praia Grande", "Guarujá", "Taubaté", "Limeira",
        "Suzano", "Taboão da Serra", "Sumaré", "Barueri",
        "Embu das Artes", "Indaiatuba", "Cotia", "Americana",
        "Marília", "Araraquara", "Jacareí", "Hortolândia",
        "Presidente Prudente", "Rio Claro", "Araçatuba",
        "Santa Bárbara d'Oeste", "Ferraz de Vasconcelos",
        "Francisco Morato", "Itapecerica da Serra", "Itu",
        "Bragança Paulista", "Pindamonhangaba", "Itapevi",
        "São Carlos", "Botucatu", "Atibaia", "Valinhos",
        "Cubatão", "Santana de Parnaíba", "Sertãozinho",
        "Catanduva", "Assis", "Jaú", "Ourinhos", "Birigui",
        "Leme", "Votorantim", "Várzea Paulista", "Itatiba",
        "Bertioga", "São Caetano do Sul", "Mogi Guaçu", "Salto",
        "Franco da Rocha", "Poá", "Cajamar", "Caraguatatuba",
        "Mongaguá", "Itanhaém", "Peruíbe", "São Roque",
        "Votuporanga", "Penápolis", "Bebedouro", "Lins", "Tupã",
        "Registro", "Olímpia", "Lorena", "Cruzeiro", "Amparo",
        "Itapetininga", "Tatuí", "Capivari", "São Sebastião",
        "Ubatuba", "Ilhabela", "Campos do Jordão",
        "Jaguariúna", "Vinhedo", "Louveira", "Paulínia",
        "Nova Odessa", "Holambra", "Pedreira", "Serra Negra",
        "Águas de Lindóia", "Monte Mor",
    ],
    "TO": [
        "Palmas", "Araguaína", "Gurupi", "Porto Nacional",
        "Paraíso do Tocantins", "Colinas do Tocantins", "Guaraí",
        "Dianópolis", "Miracema do Tocantins", "Tocantinópolis",
        "Augustinópolis", "Formoso do Araguaia", "Pedro Afonso",
        "Taguatinga", "Arraias",
    ],
}
